name: 'International Concierge & Logistics'
favicon: null
layout_spectrum: 0.0584864504635334
typography_spectrum: 0.3199431379325688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3725736578926444
  lightness: 0.3194711026735604
  saturation: 0.9303862198721617
  rhythmicContrast: 0.7337228192482144
purpose: []
